# Generated by Django 4.0.2 on 2022-02-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_ponto_tur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='ponto_tur',
        ),
    ]
