# Generated by Django 4.0.2 on 2022-02-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_eventos_evento'),
        ('ponto_turisticos', '0002_alter_pontoturistico_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='eventos',
            field=models.ManyToManyField(to='eventos.Evento'),
        ),
    ]
