# Generated by Django 4.0.2 on 2022-02-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('ponto_turisticos', '0003_pontoturistico_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='localizacao.localizacao'),
            preserve_default=False,
        ),
    ]
