# Generated by Django 4.0.2 on 2022-02-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_alter_avaliacao_nota'),
        ('comentarios', '0003_remove_comentario_ponto_tur'),
        ('ponto_turisticos', '0007_alter_pontoturistico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
